Update GHA workflow

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -49,6 +49,43 @@ jobs:
           # Builds on other branches will only read existing entries from the cache.
           cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}
 
+      - name: Set up Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: '22'
+
+      - name: Set up ArkAnalyzer
+        run: |
+          REPO_URL="https://gitee.com/openharmony-sig/arkanalyzer.git"
+          DEST_DIR="arkanalyzer"
+          MAX_RETRIES=10
+          RETRY_DELAY=5  # Delay between retries in seconds
+
+          for ((i=1; i<=MAX_RETRIES; i++)); do
+              git clone --depth=1 $REPO_URL $DEST_DIR && break
+              echo "Clone failed, retrying in $RETRY_DELAY seconds..."
+              sleep "$RETRY_DELAY"
+          done
+          
+          if [[ $i -gt $MAX_RETRIES ]]; then
+              echo "Failed to clone the repository after $MAX_RETRIES attempts."
+              exit 1
+          else
+              echo "Repository cloned successfully."
+          fi
+          
+          cd $DEST_DIR
+          
+          # checkout master on 2024-07-17
+          rev=a9d9fd6070fce5896d8e760ed7fd175b62b16605
+          git fetch --depth=1 origin $rev
+          git switch --detach $rev
+          
+          npm install
+          npm run build
+          
+          echo "ARKANALYZER_DIR=$DEST_DIR" >> $GITHUB_ENV
+
       - name: Build and run tests
         run: ./gradlew build --stacktrace --scan
 
@@ -111,61 +148,3 @@ jobs:
         with:
           files: "**/build/test-results/**/*.xml"
           check_name: "Lifecycle test results"
-
-  build-ets:
-    name: Build and run jacodb-ets
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Set up Java
-        uses: actions/setup-java@v4
-        with:
-          java-version: 8
-          distribution: 'zulu'
-
-      - name: Set up Gradle
-        uses: gradle/actions/setup-gradle@v3
-
-      - name: Set up Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: '22'
-
-      - name: Set up ArkAnalyzer
-        run: |
-          REPO_URL="https://gitee.com/openharmony-sig/arkanalyzer.git"
-          DEST_DIR="arkanalyzer"
-          MAX_RETRIES=10
-          RETRY_DELAY=5  # Delay between retries in seconds
-
-          for ((i=1; i<=MAX_RETRIES; i++)); do
-              git clone --depth=1 $REPO_URL $DEST_DIR && break
-              echo "Clone failed, retrying in $RETRY_DELAY seconds..."
-              sleep "$RETRY_DELAY"
-          done
-
-          if [[ $i -gt $MAX_RETRIES ]]; then
-              echo "Failed to clone the repository after $MAX_RETRIES attempts."
-              exit 1
-          else
-              echo "Repository cloned successfully."
-          fi
-
-          cd $DEST_DIR
-
-          # checkout master on 2024-07-17
-          rev=a9d9fd6070fce5896d8e760ed7fd175b62b16605
-          git fetch --depth=1 origin $rev
-          git switch --detach $rev
-
-          npm install
-          npm run build
-
-          echo "ARKANALYZER_DIR=$DEST_DIR" >> $GITHUB_ENV
-
-      - name: Generate test resources for jacodb-ets module
-        run: ./gradlew :jacodb-ets:generateTestResources
-
-      - name: Build and run tests in jacodb-ets module
-        run: ./gradlew --scan :jacodb-ets:test
